import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Dados completos e realistas para a planilha de EPIs e Distribuição
DADOS_PLANILHA = [
    # 1. Cabeça e Auditivo
    {
        "descricao": "CAPACETE DE SEGURANÇA C/JUGULAR",
        "categoria": "CABECA_AUDITIVO",
        "fabricante": "MSA",
        "numero_ca": "12354",
        "validade_ca": "17/12/2026",
        "data_fabricacao": "10/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 25.0,
        "estoque_minimo": 5.0,
        "unidade": "UN",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "ABAFADOR TIPO CONCHA FLUX",
        "categoria": "CABECA_AUDITIVO",
        "fabricante": "3M",
        "numero_ca": "29706",
        "validade_ca": "28/10/2025",
        "data_fabricacao": "15/03/2022",
        "validade_epi": "5 anos",
        "estoque_real": 14.0,
        "estoque_minimo": 3.0,
        "unidade": "UN",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "PROTETOR AUDITIVO TIPO PLUG SILICONE",
        "categoria": "CABECA_AUDITIVO",
        "fabricante": "Delta Plus",
        "numero_ca": "9584",
        "validade_ca": "19/07/2026",
        "data_fabricacao": "01/06/2023",
        "validade_epi": "3 anos",
        "estoque_real": 150.0,
        "estoque_minimo": 20.0,
        "unidade": "PAR",
        "funcionario": "Marcos Vinicius Santos",
        "funcao": "Motorista de Distribuição",
        "setor": "Logística",
        "local": "Cascavel",
        "matricula": "412",
        "data_entrega": "20/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 2.0
    },
    {
        "descricao": "CAPACETE DE SEGURANÇA C/ABAFADOR E JUGULAR",
        "categoria": "CABECA_AUDITIVO",
        "fabricante": "Camper",
        "numero_ca": "29638",
        "validade_ca": "15/10/2026",
        "data_fabricacao": "20/02/2023",
        "validade_epi": "5 anos",
        "estoque_real": 10.0,
        "estoque_minimo": 2.0,
        "unidade": "UN",
        "funcionario": "Francisco Raimundo Costa",
        "funcao": "Mecânico de Manutenção",
        "setor": "Oficina",
        "local": "Cascavel",
        "matricula": "705",
        "data_entrega": "02/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "SUSPENSÃO PARA CAPACETE C/ JUGULAR",
        "categoria": "CABECA_AUDITIVO",
        "fabricante": "MSA",
        "numero_ca": "12354",
        "validade_ca": "17/12/2026",
        "data_fabricacao": "05/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 32.0,
        "estoque_minimo": 10.0,
        "unidade": "UN",
        "funcionario": "Roberto Alves de Souza",
        "funcao": "Ajudante de Entrega",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "389",
        "data_entrega": "05/02/2026",
        "motivo": "TR - Troca Periódica",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },

    # 2. Ocular e Respiratório
    {
        "descricao": "OCULOS DE SEGURANÇA INCOLOR ANTI-EMBAÇANTE",
        "categoria": "OCULAR_RESPIRATORIO",
        "fabricante": "Kalipso",
        "numero_ca": "9722",
        "validade_ca": "14/08/2027",
        "data_fabricacao": "10/05/2023",
        "validade_epi": "5 anos",
        "estoque_real": 45.0,
        "estoque_minimo": 10.0,
        "unidade": "UN",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "OCULOS DE SEGURANÇA ESCURO FUMÊ UV",
        "categoria": "OCULAR_RESPIRATORIO",
        "fabricante": "Kalipso",
        "numero_ca": "9722",
        "validade_ca": "14/08/2027",
        "data_fabricacao": "10/05/2023",
        "validade_epi": "5 anos",
        "estoque_real": 38.0,
        "estoque_minimo": 10.0,
        "unidade": "UN",
        "funcionario": "Marcos Vinicius Santos",
        "funcao": "Motorista de Distribuição",
        "setor": "Logística",
        "local": "Cascavel",
        "matricula": "412",
        "data_entrega": "20/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "RESPIRADOR SEMI FACIAL CG 306",
        "categoria": "OCULAR_RESPIRATORIO",
        "fabricante": "Carbografite",
        "numero_ca": "7072",
        "validade_ca": "31/12/2026",
        "data_fabricacao": "12/04/2023",
        "validade_epi": "5 anos",
        "estoque_real": 8.0,
        "estoque_minimo": 2.0,
        "unidade": "UN",
        "funcionario": "Daniel Ribeiro Lima",
        "funcao": "Eletricista de Manutenção",
        "setor": "Manutenção Geral",
        "local": "Cascavel",
        "matricula": "442",
        "data_entrega": "10/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "M",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CARTUCHO RC 203 VAPORES ORGANICOS E GASES ACIDOS",
        "categoria": "OCULAR_RESPIRATORIO",
        "fabricante": "Carbografite",
        "numero_ca": "7072",
        "validade_ca": "31/12/2026",
        "data_fabricacao": "15/02/2023",
        "validade_epi": "3 anos",
        "estoque_real": 18.0,
        "estoque_minimo": 4.0,
        "unidade": "PAR",
        "funcionario": "Daniel Ribeiro Lima",
        "funcao": "Eletricista de Manutenção",
        "setor": "Manutenção Geral",
        "local": "Cascavel",
        "matricula": "442",
        "data_entrega": "10/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Padrão",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "MÁSCARA DE SOLDA AUTOMÁTICA REGULÁVEL",
        "categoria": "OCULAR_RESPIRATORIO",
        "fabricante": "Boxer",
        "numero_ca": "46580",
        "validade_ca": "10/11/2027",
        "data_fabricacao": "01/03/2023",
        "validade_epi": "5 anos",
        "estoque_real": 5.0,
        "estoque_minimo": 1.0,
        "unidade": "UN",
        "funcionario": "Tiago Fernandes Barbosa",
        "funcao": "Soldador Industrial",
        "setor": "Manutenção",
        "local": "Cascavel",
        "matricula": "631",
        "data_entrega": "12/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "RESPIRADOR DESCARTÁVEL PFF2 C/ VÁLVULA (NR-95)",
        "categoria": "OCULAR_RESPIRATORIO",
        "fabricante": "3M",
        "numero_ca": "41514",
        "validade_ca": "22/09/2026",
        "data_fabricacao": "18/07/2023",
        "validade_epi": "3 anos",
        "estoque_real": 90.0,
        "estoque_minimo": 25.0,
        "unidade": "UN",
        "funcionario": "Lucas Pereira de Lima",
        "funcao": "Operador de Empilhadeira",
        "setor": "Expedição",
        "local": "Cascavel",
        "matricula": "620",
        "data_entrega": "03/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 2.0
    },

    # 3. Luvas e Proteção Manual
    {
        "descricao": "LUVA DE PROTEÇÃO TRIC PRETA",
        "categoria": "LUVAS",
        "fabricante": "Volk",
        "numero_ca": "30916",
        "validade_ca": "21/01/2026",
        "data_fabricacao": "05/02/2023",
        "validade_epi": "5 anos",
        "estoque_real": 70.0,
        "estoque_minimo": 15.0,
        "unidade": "PAR",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "G",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "LUVA DE VAQUETA CANO CURTO",
        "categoria": "LUVAS",
        "fabricante": "Zanel",
        "numero_ca": "20004",
        "validade_ca": "14/05/2026",
        "data_fabricacao": "11/03/2023",
        "validade_epi": "3 anos",
        "estoque_real": 40.0,
        "estoque_minimo": 10.0,
        "unidade": "PAR",
        "funcionario": "Antônio José Ferreira",
        "funcao": "Conferente de Carga",
        "setor": "Armazém",
        "local": "Cascavel",
        "matricula": "508",
        "data_entrega": "18/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "10",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "LUVA DE PROTEÇÃO EM PVC CANO LONGO 35CM",
        "categoria": "LUVAS",
        "fabricante": "Danny",
        "numero_ca": "37127",
        "validade_ca": "05/08/2025",
        "data_fabricacao": "14/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 22.0,
        "estoque_minimo": 5.0,
        "unidade": "PAR",
        "funcionario": "Francisco Raimundo Costa",
        "funcao": "Mecânico de Manutenção",
        "setor": "Oficina",
        "local": "Cascavel",
        "matricula": "705",
        "data_entrega": "02/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "9.5",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "LUVA TRIC MAXGRIP VERDE ALTA ADERÊNCIA",
        "categoria": "LUVAS",
        "fabricante": "Mucambo",
        "numero_ca": "16314",
        "validade_ca": "18/11/2026",
        "data_fabricacao": "22/04/2023",
        "validade_epi": "5 anos",
        "estoque_real": 55.0,
        "estoque_minimo": 12.0,
        "unidade": "PAR",
        "funcionario": "Lucas Pereira de Lima",
        "funcao": "Operador de Empilhadeira",
        "setor": "Expedição",
        "local": "Cascavel",
        "matricula": "620",
        "data_entrega": "03/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "G",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "LUVA DE PROTEÇÃO ANTICORTE NÍVEL 5",
        "categoria": "LUVAS",
        "fabricante": "Danny",
        "numero_ca": "38201",
        "validade_ca": "09/06/2027",
        "data_fabricacao": "10/06/2023",
        "validade_epi": "5 anos",
        "estoque_real": 30.0,
        "estoque_minimo": 8.0,
        "unidade": "PAR",
        "funcionario": "Marcelo Soares de Oliveira",
        "funcao": "Auxiliar de Logística",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "515",
        "data_entrega": "06/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "M",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "LUVA MOTOQUEIRO C/ PROTEÇÃO DE DORSO",
        "categoria": "LUVAS",
        "fabricante": "X11",
        "numero_ca": "44102",
        "validade_ca": "12/03/2027",
        "data_fabricacao": "01/02/2023",
        "validade_epi": "3 anos",
        "estoque_real": 16.0,
        "estoque_minimo": 4.0,
        "unidade": "PAR",
        "funcionario": "Paulo Henrique Gomes",
        "funcao": "Motoboy / Entregador Expresso",
        "setor": "Encomendas",
        "local": "Cascavel",
        "matricula": "298",
        "data_entrega": "08/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "G",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CREME DE PROTEÇÃO GRUPO 3 P/ MÃOS LUVEX",
        "categoria": "LUVAS",
        "fabricante": "Luvex",
        "numero_ca": "41147",
        "validade_ca": "11/10/2026",
        "data_fabricacao": "15/05/2023",
        "validade_epi": "2 anos",
        "estoque_real": 24.0,
        "estoque_minimo": 6.0,
        "unidade": "UN",
        "funcionario": "Francisco Raimundo Costa",
        "funcao": "Mecânico de Manutenção",
        "setor": "Oficina",
        "local": "Cascavel",
        "matricula": "705",
        "data_entrega": "02/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "200g",
        "qtd_entregue": 1.0
    },

    # 4. Calçados e Botas
    {
        "descricao": "BOTA DE SEGURANÇA Nº37",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 6.0,
        "estoque_minimo": 1.0,
        "unidade": "PAR",
        "funcionario": "Anderson Barbosa de Melo",
        "funcao": "Ajudante de Carga",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "354",
        "data_entrega": "14/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "37",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE SEGURANÇA Nº38",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 9.0,
        "estoque_minimo": 4.0,
        "unidade": "PAR",
        "funcionario": "Roberto Alves de Souza",
        "funcao": "Ajudante de Entrega",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "389",
        "data_entrega": "05/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "38",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE SEGURANÇA Nº39",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 14.0,
        "estoque_minimo": 5.0,
        "unidade": "PAR",
        "funcionario": "Lucas Pereira de Lima",
        "funcao": "Operador de Empilhadeira",
        "setor": "Expedição",
        "local": "Cascavel",
        "matricula": "620",
        "data_entrega": "03/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "39",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE SEGURANÇA Nº40",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 18.0,
        "estoque_minimo": 5.0,
        "unidade": "PAR",
        "funcionario": "Antônio José Ferreira",
        "funcao": "Conferente de Carga",
        "setor": "Armazém",
        "local": "Cascavel",
        "matricula": "508",
        "data_entrega": "18/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "40",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE SEGURANÇA Nº41",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 16.0,
        "estoque_minimo": 5.0,
        "unidade": "PAR",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "41",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE SEGURANÇA Nº42",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 12.0,
        "estoque_minimo": 4.0,
        "unidade": "PAR",
        "funcionario": "Marcos Vinicius Santos",
        "funcao": "Motorista de Distribuição",
        "setor": "Logística",
        "local": "Cascavel",
        "matricula": "412",
        "data_entrega": "20/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "42",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE SEGURANÇA Nº43",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "32807",
        "validade_ca": "14/11/2026",
        "data_fabricacao": "15/01/2023",
        "validade_epi": "3 anos",
        "estoque_real": 8.0,
        "estoque_minimo": 3.0,
        "unidade": "PAR",
        "funcionario": "João Paulo Martins",
        "funcao": "Motorista Carreteiro",
        "setor": "Transporte Rodoviário",
        "local": "Matriz",
        "matricula": "810",
        "data_entrega": "11/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "43",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA DE BORRACHA 7 LÉGUAS CANO MÉDIO Nº41",
        "categoria": "CALCADOS",
        "fabricante": "Alpargatas",
        "numero_ca": "30140",
        "validade_ca": "20/08/2026",
        "data_fabricacao": "03/03/2023",
        "validade_epi": "4 anos",
        "estoque_real": 10.0,
        "estoque_minimo": 2.0,
        "unidade": "PAR",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "28/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "41",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "BOTA COURO C/ BIQUEIRA KADESH CANO CURTO / ESCRITÓRIO",
        "categoria": "CALCADOS",
        "fabricante": "Kadesh",
        "numero_ca": "39210",
        "validade_ca": "05/10/2026",
        "data_fabricacao": "10/02/2023",
        "validade_epi": "3 anos",
        "estoque_real": 6.0,
        "estoque_minimo": 2.0,
        "unidade": "PAR",
        "funcionario": "Daniel Ribeiro Lima",
        "funcao": "Eletricista de Manutenção",
        "setor": "Manutenção Geral",
        "local": "Cascavel",
        "matricula": "442",
        "data_entrega": "10/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "41",
        "qtd_entregue": 1.0
    },

    # 5. Ergonomia e Vestimentas
    {
        "descricao": "CINTA ERGONOMICA TAM-P",
        "categoria": "ERGONOMIA_VESTIMENTAS",
        "fabricante": "Steelflex",
        "numero_ca": "41209",
        "validade_ca": "18/04/2027",
        "data_fabricacao": "25/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 8.0,
        "estoque_minimo": 3.0,
        "unidade": "UN",
        "funcionario": "Anderson Barbosa de Melo",
        "funcao": "Ajudante de Carga",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "354",
        "data_entrega": "14/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "P",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CINTA ERGONOMICA TAM-M",
        "categoria": "ERGONOMIA_VESTIMENTAS",
        "fabricante": "Steelflex",
        "numero_ca": "41209",
        "validade_ca": "18/04/2027",
        "data_fabricacao": "25/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 15.0,
        "estoque_minimo": 4.0,
        "unidade": "UN",
        "funcionario": "Roberto Alves de Souza",
        "funcao": "Ajudante de Entrega",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "389",
        "data_entrega": "05/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "M",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CINTA ERGONOMICA TAM-G",
        "categoria": "ERGONOMIA_VESTIMENTAS",
        "fabricante": "Steelflex",
        "numero_ca": "41209",
        "validade_ca": "18/04/2027",
        "data_fabricacao": "25/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 20.0,
        "estoque_minimo": 5.0,
        "unidade": "UN",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "G",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CINTA ERGONOMICA TAM-XG",
        "categoria": "ERGONOMIA_VESTIMENTAS",
        "fabricante": "Steelflex",
        "numero_ca": "41209",
        "validade_ca": "18/04/2027",
        "data_fabricacao": "25/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 12.0,
        "estoque_minimo": 3.0,
        "unidade": "UN",
        "funcionario": "Antônio José Ferreira",
        "funcao": "Conferente de Carga",
        "setor": "Armazém",
        "local": "Cascavel",
        "matricula": "508",
        "data_entrega": "18/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "XG",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "AVENTAL DE PVC FORRADO BRANCO",
        "categoria": "ERGONOMIA_VESTIMENTAS",
        "fabricante": "Brascamp",
        "numero_ca": "28303",
        "validade_ca": "15/10/2025",
        "data_fabricacao": "12/03/2023",
        "validade_epi": "3 anos",
        "estoque_real": 16.0,
        "estoque_minimo": 4.0,
        "unidade": "UN",
        "funcionario": "Marcelo Soares de Oliveira",
        "funcao": "Auxiliar de Logística",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "515",
        "data_entrega": "06/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "1,20x0,70m",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CAPA DE CHUVA REFORÇADA EM PVC C/ CAPUZ",
        "categoria": "ERGONOMIA_VESTIMENTAS",
        "fabricante": "Brascamp",
        "numero_ca": "28441",
        "validade_ca": "27/06/2026",
        "data_fabricacao": "14/04/2023",
        "validade_epi": "5 anos",
        "estoque_real": 22.0,
        "estoque_minimo": 5.0,
        "unidade": "UN",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "25/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "G",
        "qtd_entregue": 1.0
    },

    # 6. Outros EPIs Especiais
    {
        "descricao": "JOELHEIRA (MOTOQUEIRO)",
        "categoria": "OUTROS",
        "fabricante": "Pro Tork",
        "numero_ca": "42109",
        "validade_ca": "04/09/2026",
        "data_fabricacao": "10/01/2023",
        "validade_epi": "4 anos",
        "estoque_real": 12.0,
        "estoque_minimo": 3.0,
        "unidade": "PAR",
        "funcionario": "Paulo Henrique Gomes",
        "funcao": "Motoboy / Entregador Expresso",
        "setor": "Encomendas",
        "local": "Cascavel",
        "matricula": "298",
        "data_entrega": "08/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "COTOVELEIRA (MOTOQUEIRO)",
        "categoria": "OUTROS",
        "fabricante": "Pro Tork",
        "numero_ca": "42110",
        "validade_ca": "04/09/2026",
        "data_fabricacao": "10/01/2023",
        "validade_epi": "4 anos",
        "estoque_real": 12.0,
        "estoque_minimo": 3.0,
        "unidade": "PAR",
        "funcionario": "Paulo Henrique Gomes",
        "funcao": "Motoboy / Entregador Expresso",
        "setor": "Encomendas",
        "local": "Cascavel",
        "matricula": "298",
        "data_entrega": "08/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Único",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "CORTA PIPAS",
        "categoria": "OUTROS",
        "fabricante": "Jojafer",
        "numero_ca": "ISENTO",
        "validade_ca": "ISENTO",
        "data_fabricacao": "02/01/2023",
        "validade_epi": "5 anos",
        "estoque_real": 15.0,
        "estoque_minimo": 3.0,
        "unidade": "UN",
        "funcionario": "Paulo Henrique Gomes",
        "funcao": "Motoboy / Entregador Expresso",
        "setor": "Encomendas",
        "local": "Cascavel",
        "matricula": "298",
        "data_entrega": "08/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Retrátil Inox",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "PROTETOR SOLAR FPS 60 C/ REPELENTE 1 LITRO",
        "categoria": "OUTROS",
        "fabricante": "Luvex",
        "numero_ca": "ISENTO",
        "validade_ca": "ISENTO",
        "data_fabricacao": "01/06/2023",
        "validade_epi": "2 anos",
        "estoque_real": 14.0,
        "estoque_minimo": 4.0,
        "unidade": "UN",
        "funcionario": "DJDJDJ",
        "funcao": "Ajudante de Motorista",
        "setor": "Distribuição",
        "local": "Cascavel",
        "matricula": "373",
        "data_entrega": "15/01/2026",
        "motivo": "A - Admissão",
        "tamanho": "1L",
        "qtd_entregue": 1.0
    },
    {
        "descricao": "PERNEIRA DE SEGURANÇA EM COURO SINTÉTICO C/ TALA",
        "categoria": "CALCADOS",
        "fabricante": "Zanel",
        "numero_ca": "14758",
        "validade_ca": "23/11/2026",
        "data_fabricacao": "20/03/2023",
        "validade_epi": "4 anos",
        "estoque_real": 15.0,
        "estoque_minimo": 4.0,
        "unidade": "PAR",
        "funcionario": "João Paulo Martins",
        "funcao": "Motorista Carreteiro",
        "setor": "Transporte Rodoviário",
        "local": "Matriz",
        "matricula": "810",
        "data_entrega": "11/02/2026",
        "motivo": "A - Admissão",
        "tamanho": "Padrão",
        "qtd_entregue": 1.0
    }
]

def criar_planilha():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Controle_EPIs_e_Distribuicao"

    # Estilos
    cor_cabecalho = "0F172A"      # Slate 900
    cor_cabecalho_func = "1E3A8A" # Blue 900
    
    fill_epi = PatternFill(start_color=cor_cabecalho, end_color=cor_cabecalho, fill_type="solid")
    fill_func = PatternFill(start_color=cor_cabecalho_func, end_color=cor_cabecalho_func, fill_type="solid")
    
    font_header = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    font_data = Font(name="Calibri", size=11)
    font_bold = Font(name="Calibri", size=11, bold=True)
    
    border_thin = Side(border_style="thin", color="CBD5E1")
    cell_border = Border(left=border_thin, right=border_thin, top=border_thin, bottom=border_thin)
    
    fill_zebra = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")

    colunas = [
        ("Descricao do EPI", "epi"),
        ("Categoria", "epi"),
        ("Fabricante", "epi"),
        ("Numero CA", "epi"),
        ("Validade CA", "epi"),
        ("Data de Fabricacao", "epi"),
        ("Validade EPI", "epi"),
        ("Estoque Real", "epi"),
        ("Estoque Minimo", "epi"),
        ("Unidade", "epi"),
        ("Nome do Funcionario", "func"),
        ("Funcao", "func"),
        ("Setor", "func"),
        ("Local", "func"),
        ("Matricula", "func"),
        ("Data de Entrega", "func"),
        ("Motivo", "func"),
        ("Tamanho", "func"),
        ("Qtd Entregue", "func"),
    ]

    # Escrever Cabeçalho (Linha 1)
    for col_idx, (col_nome, tipo) in enumerate(colunas, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_nome)
        cell.font = font_header
        cell.fill = fill_func if tipo == "func" else fill_epi
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = cell_border

    ws.row_dimensions[1].height = 28

    # Escrever Dados (Linha 2 em diante)
    for row_idx, item in enumerate(DADOS_PLANILHA, 2):
        valores = [
            item["descricao"],
            item["categoria"],
            item["fabricante"],
            item["numero_ca"],
            item["validade_ca"],
            item["data_fabricacao"],
            item["validade_epi"],
            item["estoque_real"],
            item["estoque_minimo"],
            item["unidade"],
            item["funcionario"],
            item["funcao"],
            item["setor"],
            item["local"],
            item["matricula"],
            item["data_entrega"],
            item["motivo"],
            item["tamanho"],
            item["qtd_entregue"]
        ]

        zebra = (row_idx % 2 == 0)
        for col_idx, val in enumerate(valores, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = font_data
            cell.border = cell_border
            if zebra:
                cell.fill = fill_zebra
            
            # Alinhamentos
            if col_idx in (4, 5, 6, 7, 10, 15, 16, 17, 18):
                cell.alignment = Alignment(horizontal="center", vertical="center")
            elif col_idx in (8, 9, 19):
                cell.alignment = Alignment(horizontal="right", vertical="center")
            else:
                cell.alignment = Alignment(horizontal="left", vertical="center")

        ws.row_dimensions[row_idx].height = 20

    # Ajustar largura das colunas automaticamente
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 14)

    # Congelar cabeçalho
    ws.freeze_panes = "A2"

    # Salvar nos destinos
    destinos = [
        r"c:\Users\iarle\Desktop\SITE - IRMÃOS BARREIROS\Planilha_EPIs_e_Funcionarios.xlsx",
        r"c:\Users\iarle\Desktop\Planilha_EPIs_e_Funcionarios.xlsx",
        r"c:\Users\iarle\Desktop\SITE - IRMÃOS BARREIROS\frontend\meu-projeto\public\Planilha_EPIs_e_Funcionarios.xlsx"
    ]

    for d in destinos:
        try:
            os.makedirs(os.path.dirname(d), exist_ok=True)
            wb.save(d)
            print(f"Planilha salva com sucesso em: {d}")
        except Exception as e:
            print(f"Erro ao salvar em {d}: {e}")

if __name__ == "__main__":
    criar_planilha()
