// Definições oficiais dos 5 tipos de Permissão de Trabalho (PTs)
// Baseadas nos documentos técnicos e padrões de Segurança do Trabalho (NR-35, NR-33, NR-10, NR-18, NR-20)
// Distribuidora Irmãos Barreiro

export const TIPOS_PT = {
  ALTURA: {
    id: 'ALTURA',
    label: 'PTE - TRABALHO EM ALTURA',
    subtitulo: 'CUIDADOS OBRIGATÓRIOS PARA ATIVIDADES EM ALTURA (NR-35)',
    corTema: 'blue',
    hexCor: '#1d4ed8',
    revisao: 'Revisão: 02',
    vias: '1ª Via Branca - Executante do Serviço | 2ª Via Amarela - Segurança do Trabalho',
    epis: [
      'Cinto de segurança tipo paraquedista',
      'Talabarte duplo com absorvedor',
      'Capacete de segurança com jugular',
      'Bota de segurança com biqueira',
      'Óculos de proteção ampla visão',
      'Luva de vaqueta / mista',
      'Trava-quedas para corda / cabo de aço',
      'Linha de vida instalada e certificada',
      'Protetor auditivo',
    ],
    epcs: [
      'Fitas e cones de isolamento de área',
      'Sinalização de segurança / perigo queda',
      'Guarda-corpo e rodapé normatizados',
      'Rede ou tela de proteção contra queda de materiais',
      'Pontos de ancoragem inspecionados',
      'Andaime travado, nivelado e com rodapé',
      'Maca rígida de emergência',
      'Rádios de comunicação',
    ],
    itensMedidasControle: [
      '1 - A área sob o trabalho foi devidamente isolada e sinalizada contra queda de ferramentas e objetos?',
      '2 - Todos os colaboradores possuem ASO e capacitação válida para trabalho em altura conforme NR-35?',
      '3 - Os pontos de ancoragem foram inspecionados e suportam a carga mínima necessária (mínimo 1.500 kgf)?',
      '4 - O cinto de segurança e os talabartes foram inspecionados antes do uso e não apresentam desgaste ou costuras rompidas?',
      '5 - As escadas, andaimes ou plataformas estão em perfeitas condições de conservação, travadas e niveladas?',
      '6 - Existe plano de resgate e emergência definido e a equipe foi previamente orientada?',
      '7 - As condições climáticas no local estão favoráveis (ausência de vento forte, chuva ou descargas atmosféricas)?',
      '8 - As linhas elétricas aéreas próximas foram identificadas, desenergizadas ou isoladas?',
      '9 - Todas as ferramentas, baldes e peças soltas estão amarradas com cordins para evitar quedas acidentais?',
      '10 - O acesso e circulação no nível elevado estão seguros, desobstruídos e com piso antiderrapante?',
      '11 - Foi verificado se o colaborador não apresenta mal-estar, vertigem ou condições impeditivas no momento?',
      '12 - Existe supervisor ou vigia acompanhando o trabalho contínuo no solo?',
    ],
  },

  ESPACO_CONFINADO: {
    id: 'ESPACO_CONFINADO',
    label: 'PTE - ESPAÇO CONFINADO',
    subtitulo: 'CUIDADOS OBRIGATÓRIOS PARA ATIVIDADES EM ESPAÇO CONFINADO',
    corTema: 'emerald',
    hexCor: '#15803d',
    revisao: 'Revisão: 03',
    vias: '1ª Via Branca - Executante do Trabalho | 2ª Via Amarela - Vigia do Trabalho | 3ª Via Cinza - Segurança do Trabalho',
    epis: [
      'Bota de segurança',
      'Luva de proteção',
      'Capacete com jugular',
      'Cinturão de segurança tipo paraquedista',
      'Óculos de proteção',
      'Calça-jaqueta de PVC',
      'Máscara respiratória autônoma / linha de ar',
      'Protetor auditivo',
    ],
    epcs: [
      'Tripé de resgate com guincho redutor',
      'Trava-quedas retrátil para resgate',
      'Sistema de ventilação / exaustão forçada',
      'Medidor multigás calibrado (O2, CO, H2S, LIE)',
      'Lanterna intrinsecamente segura',
      'Rádios de comunicação intrinsecamente seguros',
      'Cones e fitas de sinalização',
      'Alarme sonoro de emergência',
    ],
    itensMedidasControle: [
      '1 - Existe iluminação adequada e à prova de explosão para o espaço confinado?',
      '2 - Os trabalhadores envolvidos receberam treinamento de Segurança em Espaço Confinado (Dentro da validade - NR-33)?',
      '3 - Está disponível equipamento de proteção respiratória/autônoma para a equipe de resgate?',
      '4 - O local possui extintor de incêndio próximo e adequado a respectiva classe de fogo que possa existir?',
      '5 - Os colaboradores envolvidos no trabalho utilizam o Cinturão de Segurança tipo Pára-quedista preso a um cabo p/ içamento p/ cima ou lateral?',
      '6 - Fontes de energia estão isoladas e as linhas bloqueadas, travadas e etiquetadas (LOTO)?',
      '7 - Os Equipamentos de monitoramento de gases estão calibrados e aprovados por organismo de certificação credenciado pelo INMETRO p/ trabalho em área com potencial explosivo (dentro da validade de calibração)?',
      '8 - Equipamentos de comunicação são aprovados e certificados por organismo de certificação credenciado pelo INMETRO para trabalho em área com potencial explosivo?',
      '9 - Existe sistema de Ventilação/Exaustão operando e garantindo atmosfera segura?',
      '10 - Necessita da utilização de Escada?',
      '11 - O trabalho em Espaço Confinado está em conformidade com os requisitos para entrada nos locais?',
      '12 - Lanterna, rádio de comunicação e outros equipamentos usados dentro do Espaço confinado são Intrinsecamente Seguros?',
      '13 - A área foi devidamente isolada ou sinalizada?',
      '14 - A atmosfera explosiva foi eliminada e testada?',
      '15 - As pessoas foram informadas sobre os riscos, e estão protegidas corretamente para desenvolver suas atividades no espaço confinado?',
      '16 - Existe sistema/equipamentos para realizar a movimentação vertical / suportes externos (Tripé)?',
      '17 - Existem procedimentos definidos para a comunicação permanente entre executante e vigia?',
      '18 - Existem procedimentos e sistema montado para realizar o resgate imediato em caso de emergência?',
      '19 - Os funcionários estão utilizando todos os EPIs requeridos?',
      '20 - A pressão arterial e aptidão clínica foram verificadas e liberadas pelo setor de saúde ocupacional?',
    ],
  },

  ELETRICIDADE: {
    id: 'ELETRICIDADE',
    label: 'PTE - TRABALHO EM ELETRICIDADE',
    subtitulo: 'CUIDADOS OBRIGATÓRIOS PARA ATIVIDADES COM ELETRICIDADE (NR-10)',
    corTema: 'yellow',
    hexCor: '#ca8a04',
    revisao: 'Revisão: 02',
    vias: '1ª Via Branca - Documentação do Serviço | 2ª Via Amarela - Segurança do Trabalho',
    epis: [
      'Bota de couro para eletricista (sem metal)',
      'Capacete de segurança para eletricista classe B',
      'Luva de eletricista / isolante de borracha',
      'Luva de cobertura de vaqueta',
      'Fardamento retardante a chama (Risco 2)',
      'Óculos lente incolor/cinza com ampla visão',
      'Avental de PVC',
      'Cinto de segurança do tipo paraquedista dielétrico',
      'Protetor auditivo',
    ],
    epcs: [
      'Rádios de comunicação',
      'Maca de emergência',
      'Trava-quedas retrátil dielétrico',
      'Abafadores de arco elétrico',
      'Isolador de fonte / mantas isolantes',
      'Tripé de resgate',
      'Alarme sonoro de emergência',
      'Cones de sinalização e fitas zebradas',
      'Conjunto de aterramento temporário',
    ],
    itensMedidasControle: [
      '1 - Todas as fontes de energia foram identificadas (Elétrica, mecânica, hidráulica, pneumática, química, térmica, pressão)?',
      '2 - Todas as fontes de energia foram desligadas, bloqueadas ou aliviadas?',
      '3 - Todas as fontes de energia foram etiquetadas, bloqueadas e travadas com cadeados individuais?',
      '4 - Os colaboradores estão com os cadeados de segurança nos suportes de travamentos de energia?',
      '5 - O sistema foi testado com detector de ausência de tensão e está comprovadamente sem energia residual?',
      '6 - Os colaboradores estão cientes que devem retirar os cadeados somente após o término do serviço?',
      '7 - As ferramentas elétricas são apropriadas, isoladas (1000V) e estão em perfeitas condições?',
      '8 - Os cabos elétricos de alimentação estão em boas condições, sem emendas ou desencapamentos?',
      '9 - As proteções dos equipamentos e máquinas estão instaladas e em boas condições?',
      '10 - As máquinas e equipamentos têm suas partes móveis devidamente protegidas?',
      '11 - A máquina ou equipamento possui dispositivo de parada de emergência acessível?',
      '12 - Existe sinalização no local informando que o painel/máquina está em manutenção e proibido de ligar?',
      '13 - Foram analisados e protegidos todos os pontos que apresentam riscos de corte ou choque elétrico?',
      '14 - As escadas utilizadas no serviço são de fibra de vidro (não condutivas)?',
      '15 - A máquina ou equipamento onde será realizado o serviço está devidamente aterrado?',
      '16 - Foi verificado e garantido que não existe capacitância residual no circuito?',
      '17 - Os colaboradores envolvidos no serviço não utilizam adornos (anéis, relógios, cordões metálicos)?',
      '18 - Existe sistema de combate a incêndio (Extintor CO2 / PQS) próximo ao painel em manutenção?',
      '19 - Os colaboradores envolvidos estão qualificados e habilitados conforme NR-10 e com SEP quando aplicável?',
      '20 - A área está devidamente isolada com barreiras, fitas e sinalização de alta/baixa tensão?',
    ],
  },

  TRABALHO_QUENTE: {
    id: 'TRABALHO_QUENTE',
    label: 'PERMISSÃO DE TRABALHO A QUENTE',
    subtitulo: 'CONTROLE DE RISCOS DE INCÊNDIO E EXPLOSÃO (SOLDA, MAÇARICO, LIXADEIRA)',
    corTema: 'orange',
    hexCor: '#ea580c',
    revisao: 'Revisão: 01',
    vias: '1ª Via Branca - Executante do Trabalho | 2ª Via Amarela - Segurança do Trabalho',
    epis: [
      'Máscara de solda com lente tonalidade adequada',
      'Avental de raspa',
      'Mangote de raspa',
      'Perneira de raspa',
      'Luva de raspa / vaqueta para soldador',
      'Bota de segurança de couro com biqueira',
      'Óculos de proteção incolor / corte',
      'Protetor auditivo',
      'Máscara para fumos metálicos PFF2',
    ],
    epcs: [
      'Extintores de incêndio (PQS / Água / CO2) no posto imediato',
      'Biombos / tapumes antichama de proteção contra projeções',
      'Lonas antichamas para cobertura de materiais combustíveis',
      'Manta cerâmica / antichama para canaletas e ralos',
      'Detector de gases inflamáveis (Explosímetro)',
      'Sistema de exaustão localizada de fumos',
      'Fitas zebradas e cones de isolamento',
      'Válvulas corta-chama no maçarico e no cilindro',
    ],
    itensMedidasControle: [
      '1 - Os funcionários utilizam acendedor próprio de pedra para acendimento do maçarico (proibido isqueiro comum)?',
      '2 - Os sprinklers, hidrantes e extintores de incêndio disponíveis estão operacionais e testados?',
      '3 - Os extintores de incêndio são adequados à classe de fogo existente e posicionados a menos de 5 metros?',
      '4 - Pisos e arredores foram varridos e limpos de poeira de fiapos, plástico, papelão e outros combustíveis?',
      '5 - Dutos, tubulações e condutores foram desligados ou impedidos de conduzirem centelhas e faíscas?',
      '6 - Tambores, tanques ou barris estão limpos, inertizados e livres de vapores/óleos inflamáveis?',
      '7 - O executante do trabalho a quente removeu todas as fontes de ignição dos bolsos e da área imediata?',
      '8 - Aberturas em pisos/paredes no raio de 15 metros foram cobertas com encerado à prova de fogo?',
      '9 - Na impossibilidade de remover materiais combustíveis, estes foram cobertos por lona antichama?',
      '10 - Materiais combustíveis foram removidos para distância mínima de 15 metros da área a quente?',
      '11 - Se realizado em Espaço Confinado, o local cumpre os requisitos adicionais de entrada e ventilação?',
      '12 - A área foi totalmente isolada e sinalizada para impedir a passagem de pessoas não autorizadas?',
      '13 - Foi utilizada neblina d água quando necessário para resfriamento ou eliminação de gases?',
      '14 - Os funcionários utilizam cinto de segurança se o trabalho estiver acima de 1,80 metros?',
      '15 - O conjunto oxiacetileno/maçarico está em boas condições com válvulas de retenção corta-chama?',
      '16 - Foi instalado anteparo/tapume contra radiação ultravioleta e projeção de partículas incandescentes?',
      '17 - O soldador e seu ajudante estão trajando todos os EPIs de raspa e proteção facial requeridos?',
      '18 - Foi vistoriada a presença de gases ou líquidos inflamáveis em canaletas, poços e ralos próximos?',
      '19 - Foi designado Observador de Incêndio (bombeiro ou brigadista) presente durante toda a operação?',
    ],
  },

  QUIMICOS: {
    id: 'QUIMICOS',
    label: 'PTE - PRODUTOS QUÍMICOS E GASES PERIGOSOS',
    subtitulo: 'CUIDADOS OBRIGATÓRIOS PARA ATIVIDADES COM PRODUTOS QUÍMICOS E GASES PERIGOSOS',
    corTema: 'red',
    hexCor: '#dc2626',
    revisao: 'Revisão: 01',
    vias: '1ª Via Branca - Executante do Serviço | 2ª Via Amarela - Segurança do Trabalho',
    epis: [
      'Bota de couro / PVC / borracha nitrílica',
      'Luva de vaqueta / borracha / nitrílica',
      'Roupa de proteção especial para químicos / gases (Tyvek)',
      'Avental impermeável de PVC',
      'Capacete de segurança',
      'Óculos lente incolor/cinza com ampla visão contra respingos',
      'Máscara panorâmica para gases com filtros adequados',
      'Protetor auditivo',
    ],
    epcs: [
      'Ducha de emergência e lava-olhos testados e acessíveis no raio imediato',
      'Kit de mitigação de vazamento / absorventes químicos / barreiras',
      'Sistema de exaustão e lavador de gases em pleno funcionamento',
      'Sistema de medição contínua e detector de gases tóxicos/corrosivos',
      'Maca rígida de emergência',
      'Megafones e alarme sonoro de evacuação',
      'Rádios de comunicação',
      'Cones e fitas de isolamento químico',
    ],
    itensMedidasControle: [
      '1 - Todas as fontes de energia foram identificadas (mecânica, hidráulica, pneumática, química, térmica, pressão)?',
      '2 - Todas as fontes de energia química e gasosa foram desligadas, bloqueadas ou aliviadas?',
      '3 - Todas as linhas e válvulas com produto químico ou gás foram etiquetadas, flangeadas (raquete) e bloqueadas?',
      '4 - Os colaboradores estão com os cadeados de segurança individuais nos travamentos das válvulas?',
      '5 - O sistema e tubulações foram drenados, purgados e estão livres de pressão e produto residual?',
      '6 - Os colaboradores estão cientes que devem retirar os bloqueios somente após o término e teste seguro?',
      '7 - As ferramentas para uso na atividade são adequadas, antifaiscantes e em boas condições?',
      '8 - As tubulações, mangueiras e reservatórios estão em perfeitas condições, sem vazamentos ou emendas?',
      '9 - As proteções dos equipamentos e bombas estão instaladas e conferidas?',
      '10 - Existe sinalização clara no local informando que o sistema químico está em manutenção preventiva?',
      '11 - Foram analisados e neutralizados todos os pontos com risco de respingo, projeção ou inalação de vapores?',
      '12 - Em caso de acidentes, o chuveiro de emergência e lava-olhos foi testado e está desobstruído a menos de 10 segundos?',
      '13 - Os produtos químicos possuem FISPQ/FDS atualizada no local e aprovada pelo SESMT e Meio Ambiente?',
      '14 - As pessoas foram instruídas sobre os riscos toxicológicos e usam o conjunto de proteção química completo?',
      '15 - As informações e rótulos dos produtos batem com as fichas técnicas e frascos utilizados?',
      '16 - Existe ventilação/exaustão suficiente eliminando concentrações perigosas de gases na atmosfera?',
      '17 - Os colaboradores envolvidos receberam treinamento específico para manuseio seguro de produtos perigosos?',
      '18 - A área foi totalmente isolada com barreira física contra a passagem de terceiros desprotegidos?',
      '19 - Os recipientes para descarte de resíduos químicos e panos contaminados estão identificados e fechados?',
    ],
  },
};

// Texto padrão oficial que consta no verso de todas as PTEs (Página 2)
export const PROCEDIMENTO_TEXTO_PAGINA_2 = [
  '1. Todos os trabalhos de risco realizados pela Manutenção e terceiros necessitam de uma "Permissão de Trabalho Específica - PTE", formal para realização dos trabalhos nas suas respectivas áreas.',
  '2. Se os riscos não estiverem contemplados e/ou não estiverem contemplados de forma abrangente na planilha LAPID, deve ser emitida uma APR - Análise Preliminar de Riscos Ambientais e Ocupacionais. A Permissão de Trabalho Específica - PTE é uma autorização formal para execução de trabalho de risco específico, complementar à PTR - Permissão de Trabalho de Risco. A PTE autoriza o início do trabalho após serem avaliados os riscos de Segurança e Saúde e as devidas proposições de medidas de segurança aplicáveis. A PTE deve ser emitida como complementação de uma PTR geral e sempre validada por Engenheiro ou Técnico de Segurança do Trabalho.',
  '3. Na APR deve ser avaliado e garantido o atendimento aos itens estabelecidos antes da emissão da "Permissão de Trabalho Específica - PTE", obtendo as respectivas assinaturas das pessoas envolvidas.',
  '4. A PTR e PTEs têm validade diária ou por turno, somente para o local, equipamento e condições a que se destinou originalmente, dentro da data e período de trabalho nela contidos. Quando as condições previamente estabelecidas forem alteradas, devem-se abrir novas PTR e PTEs. A PTR e PTEs podem ser revalidadas no máximo por duas vezes.',
  '5. Ocorrendo a paralisação dos trabalhos por motivos de não conformidade, a "Permissão de Trabalho Específica" pode ser retirada e cancelada, sendo necessária a abertura de outra Permissão. O reinício dos trabalhos somente pode ocorrer após a solução da não conformidade e autorização dos emitentes da nova APR e PTE.',
  '6. Caso haja mudança de escopo de trabalho ou alguma nova atividade não contemplada na APR, a PTE e PTR vigentes devem ser automaticamente canceladas e uma nova PTE deve ser aberta.',
  '7. Após o término dos trabalhos, a supervisão executante deve encaminhar para o setor de segurança do trabalho a APR, PTR e PTE para arquivamento pelo período legal de 5 anos.',
  '8. As recomendações estabelecidas no formulário da APR são básicas para direcionar a emissão da PTR, bem como permitir o início dos trabalhos que, em função da natureza e complexidade do risco, exigem a emissão de PTEs específicas.',
  '9. As recomendações estabelecidas no formulário da PTE são obrigatórias quando a resposta for SIM. Se houver algum item NÃO CONFORME, o trabalho NÃO deve ser liberado até a devida adequação do item. Portanto, o responsável pela supervisão deve providenciar a adequação de todos os itens antes do acionamento dos responsáveis pela liberação da permissão.',
];
